### PR TITLE
Chore: Update example app gradle version and compile sdk version 

### PR DESCRIPTION
**Pull request by jjliu15**
## Description

- Update android compile sdk version to 30
- Update gradle version in example app

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by bparrishMines — COMMENTED** [review]
What is the rationale to updating the `compileSdkVersion`? What would be the consequences to keeping it the same. The plugins in [flutter/plugins](https://github.com/flutter/plugins) still use 29 and I wonder if this would cause incompatibility with those plugins.

**Comment by blasten** [comment]
@bparrishMines usually newer versions of the SDK provide newer warnings (API breaking changes, etc...). `compileSdkVersion` doesn't change behavior at runtime though. -  As far as having multiple plugins with different compileSdkVersion, latest Android Gradle plugin scopes the version to specific dependency, so this should be fine.

**Review by blasten — APPROVED** [review]

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by jjliu15** [comment]
Also FWIW I tried adding other plugins as a dependency to the example app and was able to build with no issues.

**Pull request merged**
