### PR TITLE
Banner hardcoded to be adaptive

### PR DESCRIPTION
**Pull request by esuljic**
## Description

I wanted to have a banner from side to side but didn't manage to do it with the current library by sending width and height. So I just hardcoded the adaptive banner implementation for android. Please implement this, but please don't take this as is, as I removed options for other banner types.

### CODE REVIEW

**Comment by esuljic** [comment]
@googlebot I signed it!

**Comment by blasten** [comment]
@esuljic do you have an example app?  Yes, doing this in the platform side isn't ideal.

**Comment by blasten** [comment]
I will close this PR, but please follow up with an issue instead.

**Comment by esuljic** [comment]
> @esuljic do you have an example app? Yes, doing this in the platform side isn't ideal.
[This](https://play.google.com/store/apps/details?id=com.calcon.scientific_calculator) is my app that uses code from this PR.

I found [this issue](https://github.com/googleads/googleads-mobile-flutter/discussions/96) already

**Pull request closed without merging**
