### PR TITLE
Use AndroidView

### PR DESCRIPTION
**Pull request by blasten**
## Description

Try this change on the Flutter master channel.

### CODE REVIEW

**Comment by blasten** [comment]
## Steps to try these changes

1. Switch to Flutter master channel
```sh
flutter channel master
flutter upgrade
```

2. Download the changes required for `google_mobile_ads`
```
git clone -b tx --single-branch https://github.com/googleads/googleads-mobile-flutter.git
```

3. Point the `google_mobile_ads` package to the location  where you cloned the plugin:
```yaml
  google_mobile_ads:
    path: <path>/googleads-mobile-flutter/packages/google_mobile_ads
```

4. Rebuild the app with any `flutter` command.

**Comment by agacemi** [comment]
This PR enhances really Ads on Android.. I hope that will be merged soonly on main branch

**Comment by blasten** [comment]
The changes have landed in the Flutter master channel.

**Comment by agacemi** [comment]
Thank you @blasten .. Do you means that tx branch merged on main branch of google-mobile-ads and thus uses AndroidView. ?! 

I tested tx branch on big project that use ads and we observes very good performance. For reason, we are waiting impatiently for new release of google_mobile_ads that contains your fix.

**Comment by kkorgol** [comment]
> The changes have landed in the Flutter master channel.

Hi @blasten,
There are no changes from this commit in plugin master channel. In that case v1.2.0 still has performance problem and high fps drops. What happened?

**Comment by ankitparmar007** [comment]
@kkorgol 
I think they have added you just need pass **useHybridComposition:true**, into AdWidget

found this source code in  google_mobile_ads/src/ad_containers.dart

 ```
if (defaultTargetPlatform == TargetPlatform.android) {
      return widget.useHybridComposition
          ? PlatformViewLink(
              viewType: viewType,
              surfaceFactory:
                  (BuildContext context, PlatformViewController controller) {
                return AndroidViewSurface(
                  controller: controller as AndroidViewController,
                  gestureRecognizers: const <
                      Factory<OneSequenceGestureRecognizer>>{},
                  hitTestBehavior: PlatformViewHitTestBehavior.opaque,
                );
              },
              onCreatePlatformView: (PlatformViewCreationParams params) {
                return PlatformViewsService.initSurfaceAndroidView(
                  id: params.id,
                  viewType: '${instanceManager.channel.name}/ad_widget',
                  layoutDirection: TextDirection.ltr,
                  creationParams: instanceManager.adIdFor(widget.ad),
                  creationParamsCodec: StandardMessageCodec(),
                )
                  ..addOnPlatformViewCreatedListener(
                      params.onPlatformViewCreated)
                  ..create();
              },
            )
          : AndroidView(
              viewType: viewType,
              creationParams: instanceManager.adIdFor(widget.ad),
              creationParamsCodec: const StandardMessageCodec(),
              clipBehavior: Clip.none,
            );
    }
```

**Pull request closed without merging**
