### PR TITLE
ci: use `ubuntu-latest` runner for `flutter` job

### PR DESCRIPTION
**Pull request by Salakar**
## Description

Change as per discussion here: https://github.com/googleads/googleads-mobile-flutter/pull/223#discussion_r632821963

cc @blasten 

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
Seems a few minutes faster compared to previous runs:

image

**Review by blasten — APPROVED** [review]
Awesome!

**Comment by blasten** [comment]
We might also be able to use Ubuntu for the Android job.

**Comment by Salakar** [comment]
> We might also be able to use Ubuntu for the Android job.

@blasten Yep I think you're right, would only need to use the macos runner if using an Android emulator - but in this case it's just build & unit tests. Want me to change it over too?

**Comment by blasten** [comment]
sgtm

**Comment by blasten** [comment]
@Salakar do you still want to update the OS ?   The Android emulators also run on Ubuntu.

**Review by jjliu15 — APPROVED** [review]

**Pull request merged**
